Opensource section addition :
buidlfyHq/buidlfy-landing pull request #21
Opened 2023-02-14 09:35 UTC by paarth17032000

- Add Opensource section and customized according to laptop and mobile
- Add Docs to navbar 
- Add github to social icons

2023-02-14 11:33 UTC, aayushmahapatra requested changes

2023-02-14 11:33 UTC, aayushmahapatra commented on components/Opensource/opensource-section.tsx
> +        There are many opportunities for designers, software engineers and
Update this to - "There are lots of opportunities for designers, developers, and enthusiasts to contribute to the Buidlfy ecosystem."

2023-02-14 11:33 UTC, aayushmahapatra commented on components/Opensource/opensource-section.tsx
> +        onClick={() => window.open("https://app.buidlfy.com", "_blank")}
This should open Github not the waitlist.

2023-02-14 13:06 UTC, rekpero requested changes
a small content change

2023-02-14 13:06 UTC, rekpero commented on components/Opensource/opensource-section.tsx
> +      <h5>Opensource</h5>
```suggestion
      <h5>We love OSS</h5>
```

2023-02-14 13:22 UTC, aayushmahapatra approved these changes
lgtm

2023-02-14 13:23 UTC, aayushmahapatra approved these changes

2023-02-15 07:29 UTC, rekpero approved these changes

2023-02-15 07:30 UTC, merged